<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-25T21:44:14 ICT" name="Suite1" finished-at="2024-09-25T21:44:51 ICT" duration-ms="37131">
    <groups>
    </groups>
    <test started-at="2024-09-25T21:44:14 ICT" name="PackageTest" finished-at="2024-09-25T21:44:51 ICT" duration-ms="37131">
      <class name="test.RunTest">
        <test-method is-config="true" signature="startTest()[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:14 ICT" name="startTest" finished-at="2024-09-25T21:44:14 ICT" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="testSetUp(java.lang.reflect.Method)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:14 ICT" name="testSetUp" finished-at="2024-09-25T21:44:23 ICT" duration-ms="9209" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.RunTest.test1(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method signature="test1(java.lang.String,java.lang.String)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:23 ICT" name="test1" data-provider="test1" finished-at="2024-09-25T21:44:27 ICT" duration-ms="3488" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[minionmatbua@gmail]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signed in successfully.] but found [Invalid Email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signed in successfully.] but found [Invalid Email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.RunTest.test1(RunTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="extracted()[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:27 ICT" name="extracted" finished-at="2024-09-25T21:44:27 ICT" duration-ms="366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extracted -->
        <test-method is-config="true" signature="testSetUp(java.lang.reflect.Method)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:27 ICT" name="testSetUp" finished-at="2024-09-25T21:44:34 ICT" duration-ms="6797" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.RunTest.test1(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method signature="test1(java.lang.String,java.lang.String)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:34 ICT" name="test1" data-provider="test1" finished-at="2024-09-25T21:44:38 ICT" duration-ms="4056" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[minionmatbua@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signed in successfully.] but found [Invalid Email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signed in successfully.] but found [Invalid Email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.RunTest.test1(RunTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="extracted()[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:38 ICT" name="extracted" finished-at="2024-09-25T21:44:38 ICT" duration-ms="199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extracted -->
        <test-method is-config="true" signature="testSetUp(java.lang.reflect.Method)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:38 ICT" name="testSetUp" finished-at="2024-09-25T21:44:46 ICT" duration-ms="7714" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.RunTest.test1(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method signature="test1(java.lang.String,java.lang.String)[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:46 ICT" name="test1" data-provider="test1" finished-at="2024-09-25T21:44:51 ICT" duration-ms="4810" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[minionmatbua@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345678]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="extracted()[pri:0, instance:test.RunTest@6933b6c6]" started-at="2024-09-25T21:44:51 ICT" name="extracted" finished-at="2024-09-25T21:44:51 ICT" duration-ms="164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extracted -->
      </class> <!-- test.RunTest -->
    </test> <!-- PackageTest -->
  </suite> <!-- Suite1 -->
</testng-results>
